# Generated by Django 3.0.2 on 2020-01-30 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 30, 5, 53, 0, 223630, tzinfo=utc)),
        ),
    ]
