# Generated by Django 3.0.2 on 2020-02-01 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200201_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 1, 16, 52, 14, 614233, tzinfo=utc)),
        ),
    ]
