# Generated by Django 3.0.2 on 2020-02-01 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200201_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 1, 16, 57, 59, 248757, tzinfo=utc)),
        ),
    ]
