# Generated by Django 3.0.2 on 2020-02-01 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200201_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 1, 18, 22, 38, 438689, tzinfo=utc)),
        ),
    ]
